"""fix_indexes_and_updated_at

Revision ID: b67c7dd2e97e
Revises: 002
Create Date: 2026-07-09 19:12:29.899238
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "b67c7dd2e97e"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deep_analyses_jd_score"), table_name="deep_analyses")
    op.add_column(
        "fast_track_results",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_fast_track_results_jd_score"), table_name="fast_track_results")
    op.drop_index(op.f("ix_resumes_injection_scan_passed"), table_name="resumes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_resumes_injection_scan_passed"), "resumes", ["injection_scan_passed"], unique=False
    )
    op.create_index(
        op.f("ix_fast_track_results_jd_score"),
        "fast_track_results",
        ["job_description_id", "score"],
        unique=False,
    )
    op.drop_column("fast_track_results", "updated_at")
    op.create_index(
        op.f("ix_deep_analyses_jd_score"),
        "deep_analyses",
        ["job_description_id", "overall_score"],
        unique=False,
    )
    # ### end Alembic commands ###
